#!/usr/bin/env python3
"""Generate spangap's partitions.csv — size-agnostic, state-less layout.

The flashed image is a **floor-sized** image (default 4 MB) that boots on any
chip >= that size; the firmware grows flash to the real size at first boot and
registers the `state` LittleFS partition itself (esp_partition_register_external,
no on-flash table entry). So the partition table here contains ONLY the things
that ship in the image, shrink-wrapped to their actual sizes:

    nvs        0x09000   0x05000     IDF internal (WiFi PHY cal)
    otadata    0x0E000   0x02000     (only with updater — selects app vs updater)
    updater    0x10000   <wrapped>   (only with updater) tiny serial-updated flasher (ota_1)
    app        ...        <wrapped>   firmware (factory, or ota_0 when updater present)
    fixed      ...        <wrapped>   read-only LittleFS (SPA + factory defaults)

`state` is deliberately absent — it lives in the upper half of flash and is
created at runtime (see statePartitionEnsure() in fs.cpp). Flash order keeps the
updater BELOW app/fixed so their shrink-wrap growth never moves the updater slot.

Two modes:
  * provisional (--app-bytes 0 --fixed-bytes 0): generous sizes filling the floor
    so the first configure can link + pack the littlefs image.
  * final (real --app-bytes/--fixed-bytes from the post-build measure): shrink-wrap
    app to 64 K and fixed to 4 K. Everything must fit the floor or it errors.

App partitions are 64 K-aligned; LittleFS partitions 4 K-aligned.
"""
import argparse
import sys
from pathlib import Path

APP_START   = 0x10000   # first app/updater partition (64K-aligned by spec)
APP_ALIGN   = 0x10000   # app slots must be 64K-aligned
DATA_ALIGN  = 0x1000    # LittleFS partitions: 4K alignment
NVS_START   = 0x9000
NVS_SIZE    = 0x5000
OTADATA_START = 0xE000
OTADATA_SIZE  = 0x2000
# Provisional reserve for the updater slot when its real size isn't known yet.
UPDATER_PROVISIONAL = 0x80000   # 512 KB — generous; shrunk in the final pass
# Provisional fixed reserve = this fraction of the floor (scales with flash so
# the first littlefs pack has room; the post-build pass shrinks it to actual).
FIXED_PROVISIONAL_DIV = 5        # 1/5 = 20% of the floor


def align_up(x: int, a: int) -> int:
    return ((x + a - 1) // a) * a


def render(flash_mb: int, updater: bool,
           app_bytes: int, fixed_bytes: int, updater_bytes: int) -> str:
    floor = flash_mb * 1024 * 1024
    provisional = (app_bytes == 0 and fixed_bytes == 0)

    rows: list[tuple[str, str, str, int, int, str]] = []
    rows.append(("nvs", "data", "nvs", NVS_START, NVS_SIZE, ""))

    offset = APP_START
    if updater:
        rows.append(("otadata", "data", "ota", OTADATA_START, OTADATA_SIZE, ""))
        # Updater slot first (low, stable) — ota_1.
        if provisional:
            usz = UPDATER_PROVISIONAL
        else:
            usz = align_up(updater_bytes, APP_ALIGN) if updater_bytes else UPDATER_PROVISIONAL
        rows.append(("updater", "app", "ota_1", offset, usz, ""))
        offset += usz
        app_sub = "ota_0"
    else:
        app_sub = "factory"

    if provisional:
        # Reserve a floor-scaled slice for fixed; app gets the rest. Generous on
        # both so the first link + littlefs pack succeed; shrunk post-build.
        fixed_sz = align_up(floor // FIXED_PROVISIONAL_DIV, DATA_ALIGN)
        app_sz = ((floor - offset - fixed_sz) // APP_ALIGN) * APP_ALIGN
        if app_sz < APP_ALIGN:
            sys.exit(f"gen-partitions: floor {flash_mb}MB too small for a provisional app")
    else:
        app_sz = align_up(app_bytes, APP_ALIGN)
        fixed_sz = align_up(fixed_bytes, DATA_ALIGN)
    rows.append(("app", "app", app_sub, offset, app_sz, ""))
    offset += app_sz

    end = offset + fixed_sz
    if end > floor:
        sys.exit(f"gen-partitions: layout ({end:#x}) exceeds {flash_mb}MB floor "
                 f"({floor:#x}) — raise CONFIG_ESPTOOLPY_FLASHSIZE or trim app/fixed")
    if fixed_sz < DATA_ALIGN:
        sys.exit("gen-partitions: fixed partition too small")
    rows.append(("fixed", "data", "spiffs", offset, fixed_sz, "readonly"))

    out = [
        "# Generated by spangap — do not edit. Size-agnostic floor image;",
        "# `state` is created at runtime (fs.cpp), not listed here.",
        f"# Floor {flash_mb}MB, updater={'on' if updater else 'off'}, "
        f"{'provisional' if provisional else 'shrink-wrapped'}",
        "#",
        "# Name,    Type, SubType, Offset,    Size,      Flags",
    ]
    for name, ty, sub, off, sz, flags in rows:
        out.append(f"{name+',':10s} {ty+',':5s} {sub+',':8s} {off:#010x}, {sz:#010x},"
                   + (f" {flags}" if flags else ""))
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--flash-mb", type=int, required=True, choices=[4, 8, 16, 32, 64, 128],
                    help="Floor size = configured CONFIG_ESPTOOLPY_FLASHSIZE (default 4)")
    ap.add_argument("--updater", choices=["y", "n"], required=True)
    ap.add_argument("--app-bytes", type=int, default=0, help="Actual app .bin size (0 = provisional)")
    ap.add_argument("--fixed-bytes", type=int, default=0, help="Actual fixed data size (0 = provisional)")
    ap.add_argument("--updater-bytes", type=int, default=0, help="Actual updater .bin size (0 = provisional)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    content = render(args.flash_mb, args.updater == "y",
                     args.app_bytes, args.fixed_bytes, args.updater_bytes)

    out = Path(args.out)
    # Skip the write when unchanged — keeps CMake from a needless reconfigure cascade.
    if out.exists() and out.read_text() == content:
        return 0
    out.write_text(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
