#!/usr/bin/env python3
"""Generate diptych's partitions.csv from flash size + OTA + app-percent.

Layout (8 MB OTA example, app=75%):

    nvs       0x09000   0x05000     20K  IDF internal (WiFi cal, PHY)
    otadata   0x0E000   0x02000      8K  OTA bootloader pointer (only if OTA)
    app0      0x10000   ...              firmware A     ─┐
    app1                                 firmware B      │ paired A/B if OTA;
    fixed_a                              LittleFS RO A   │ single partitions
    fixed_b                              LittleFS RO B  ─┘ if OTA off
    state                  0x40000    256K /state LittleFS R/W

`available = flash_total - 0x10000 - state_size` is split: app gets
app_percent%, fixed gets the rest. With OTA on, both are paired A/B (each
slot = half the share). With OTA off, each gets the full share.

App partitions must be 64K-aligned; LittleFS partitions are 4K-aligned. Any
rounding leftover is absorbed into fixed_b (or fixed, if OTA off) so the
layout fills the available range perfectly.
"""
import argparse
import sys
from pathlib import Path

APP_START = 0x10000     # first app partition (64K-aligned by spec)
APP_ALIGN = 0x10000     # OTA app slots must be 64K-aligned
DATA_ALIGN = 0x1000     # LittleFS partitions: 4K alignment
STATE_SIZE = 0x40000    # /state LittleFS R/W (256 KB)
NVS_START = 0x9000
NVS_SIZE = 0x5000
OTADATA_START = 0xE000
OTADATA_SIZE = 0x2000


def align_down(x: int, a: int) -> int:
    return (x // a) * a


def render(flash_mb: int, ota: bool, app_pct: int) -> str:
    flash_total = flash_mb * 1024 * 1024
    available = flash_total - APP_START - STATE_SIZE

    rows: list[tuple[str, str, str, int, int, str]] = []
    rows.append(("nvs", "data", "nvs", NVS_START, NVS_SIZE, ""))

    if ota:
        rows.append(("otadata", "data", "ota", OTADATA_START, OTADATA_SIZE, ""))
        # App: half of (available * pct/100), 64K-aligned
        app_slot = align_down(available * app_pct // 200, APP_ALIGN)
        if app_slot < APP_ALIGN:
            sys.exit(f"diptych gen-partitions: app slot too small ({app_slot} bytes)")
        # Remaining after 2 app slots → 2 fixed slots
        rest = available - 2 * app_slot
        fixed_a = align_down(rest // 2, DATA_ALIGN)
        # fixed_b absorbs any rounding leftover (still DATA_ALIGN-aligned).
        fixed_b = rest - fixed_a
        if fixed_a < DATA_ALIGN or fixed_b < DATA_ALIGN:
            sys.exit(f"diptych gen-partitions: fixed slots too small "
                     f"({fixed_a}/{fixed_b} bytes) — try a lower app-percent")

        offset = APP_START
        rows.append(("app0", "app", "ota_0", offset, app_slot, ""));    offset += app_slot
        rows.append(("app1", "app", "ota_1", offset, app_slot, ""));    offset += app_slot
        rows.append(("fixed_a", "data", "spiffs", offset, fixed_a, "readonly")); offset += fixed_a
        rows.append(("fixed_b", "data", "spiffs", offset, fixed_b, "readonly")); offset += fixed_b
        rows.append(("state", "data", "spiffs", offset, STATE_SIZE, ""))
    else:
        # No OTA → no otadata, single factory app, single fixed.
        app_size = align_down(available * app_pct // 100, APP_ALIGN)
        fixed_size = available - app_size
        if app_size < APP_ALIGN or fixed_size < DATA_ALIGN:
            sys.exit(f"diptych gen-partitions: app/fixed too small "
                     f"({app_size}/{fixed_size} bytes)")

        offset = APP_START
        rows.append(("factory", "app", "factory", offset, app_size, ""));   offset += app_size
        rows.append(("fixed", "data", "spiffs", offset, fixed_size, "readonly")); offset += fixed_size
        rows.append(("state", "data", "spiffs", offset, STATE_SIZE, ""))

    out = [
        "# Generated by diptych — do not edit. Tune via `idf.py menuconfig`:",
        "#   diptych modules → OTA, App share %",
        "#   Serial flasher config → Flash size",
        f"# Flash {flash_mb}MB, OTA={'on' if ota else 'off'}, app={app_pct}%",
        "#",
        "# Name,    Type, SubType, Offset,    Size,      Flags",
    ]
    for name, ty, sub, off, sz, flags in rows:
        out.append(f"{name+',':10s} {ty+',':5s} {sub+',':8s} {off:#010x}, {sz:#010x},"
                   + (f" {flags}" if flags else ""))
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--flash-mb", type=int, required=True, choices=[4, 8, 16, 32, 64, 128])
    ap.add_argument("--ota", choices=["y", "n"], required=True)
    ap.add_argument("--app-percent", type=int, required=True)
    ap.add_argument("--out", required=True, help="Output partitions.csv path")
    args = ap.parse_args()

    if not (10 <= args.app_percent <= 90):
        sys.exit(f"diptych gen-partitions: app-percent {args.app_percent} out of range (10..90)")

    content = render(args.flash_mb, args.ota == "y", args.app_percent)

    out = Path(args.out)
    # Avoid touching mtime if content unchanged — keeps CMake from triggering
    # a needless reconfigure cascade on plain rebuilds.
    if out.exists() and out.read_text() == content:
        return 0
    out.write_text(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
