#!/usr/bin/env python3
"""
Download the IANA→POSIX timezone mapping from GitHub and bake it into the
firmware as two sorted C arrays (src/timezones_gen.c). The table lives in
rodata: nothing is parsed at runtime and nothing is held in RAM — tzLookup()
(src/timezones.c) binary-searches the names in flash, and the LCD timezone
picker iterates them directly. Zone data therefore rides every firmware
update; there is no on-device zone file and no runtime refresh channel.

ETag cache (skips the download when GitHub says "not modified") goes to
<cache_dir>/.zones_etag, which defaults to <esp-idf dir>.

Usage:
    python3 update-zones.py <esp-idf dir> [--cache-dir <dir>] [--force]

A release-time step, NOT part of any build (so per-build images stay
reproducible). Run via spangap-core's `make timezones`. The generated file is
checked in; re-run only to refresh the IANA data.
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request

ZONES_URL = "https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.json"


def fetch_zones(cache_path, force):
    """Download zones.json if modified since last check.
    Returns (dict, etag) or (None, None)."""
    headers = {}
    if not force and os.path.exists(cache_path):
        with open(cache_path) as f:
            headers["If-None-Match"] = f.read().strip()

    req = urllib.request.Request(ZONES_URL, headers=headers)
    try:
        resp = urllib.request.urlopen(req, timeout=15)
    except urllib.error.HTTPError as e:
        if e.code == 304:
            print("zones.json: not modified")
            return None, None
        raise
    except (urllib.error.URLError, OSError) as e:
        print(f"zones.json: skipped (no network: {e.reason})")
        return None, None

    etag = resp.headers.get("ETag", "")
    if etag:
        os.makedirs(os.path.dirname(cache_path) or ".", exist_ok=True)
        with open(cache_path, "w") as f:
            f.write(etag)

    data = json.loads(resp.read())
    print(f"zones.json: downloaded {len(data)} zones")
    return data, etag


def cstr(s):
    """A C string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_table(out_path, zones, etag):
    """Emit the two parallel arrays, sorted by name — byte order, which is what
    tzLookup()'s strcmp binary search assumes."""
    items = sorted(zones.items())
    lines = [
        "/* Generated by scripts/update-zones.py (`make timezones`) — do not edit.",
        f" * Source: {ZONES_URL}",
        f" * Source ETag: {etag or '(unknown)'}",
        " * Sorted by name (strcmp) for tzLookup()'s binary search. */",
        '#include "timezones.h"',
        "",
        "const char* const TZ_NAMES[] = {",
    ]
    lines += [f"    {cstr(name)}," for name, _ in items]
    lines += ["};", "", "const char* const TZ_POSIX[] = {"]
    lines += [f"    {cstr(posix)}," for _, posix in items]
    lines += ["};", "", f"const int TZ_COUNT = {len(items)};", ""]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"timezones_gen.c: updated ({len(items)} zones)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out_dir", help="the esp-idf dir (writes src/timezones_gen.c under here)")
    ap.add_argument("--cache-dir", default=None,
                    help=".zones_etag location (default: out_dir)")
    ap.add_argument("--force", action="store_true",
                    help="ignore ETag cache and always re-download")
    args = ap.parse_args()

    out_dir = os.path.abspath(args.out_dir)
    cache_dir = os.path.abspath(args.cache_dir) if args.cache_dir else out_dir
    cache_path = os.path.join(cache_dir, ".zones_etag")
    out_path = os.path.join(out_dir, "src", "timezones_gen.c")

    zones, etag = fetch_zones(cache_path, args.force)
    if zones is None:
        return
    write_table(out_path, zones, etag)


if __name__ == "__main__":
    main()
