#!/usr/bin/env python3
"""Emit a tiny .c file with `app_build_unix` (UTC seconds at link time).

Wired into diptych-core's CMakeLists as an ALL custom target that re-runs
every ninja invocation, so the build epoch always reflects the current
build (ota.cpp uses it to refuse OTA images older than itself, and the
browser surfaces it as `sys.buildtime.app`).

Usage: python3 write-build-epoch.py <output.c>
"""
import sys
import time

path = sys.argv[1]
with open(path, "w", encoding="ascii") as f:
    f.write(
        "/* Generated by diptych-core/scripts/write-build-epoch.py - do not edit. */\n"
        "#include <stdint.h>\n"
        "const uint32_t app_build_unix = {}u;\n".format(int(time.time()))
    )
