#!/usr/bin/env python3
"""Emit a tiny .c file with the `spangap build` invocation identity.

Three string symbols, populated from the environment that the in-container
`spangap build` (build-system/spangap-inside cmd_build) exports around the
idf.py build it spawns:

    app_build_straddle  — the buildable straddle's <org>/<repo>  (SPANGAP_BUILD_STRADDLE)
    app_build_version   — its straddle.yaml `version:`           (SPANGAP_BUILD_VERSION)
    app_build_args      — the full `spangap build ...` command    (SPANGAP_BUILD_ARGS)

Wired into spangap-core's CMakeLists as an ALL custom target that re-runs
every ninja invocation (same mechanism as write-build-epoch.py), so the
strings always reflect the build that produced the running image.
spangap_init.cpp logs them on boot and surfaces them as sys.build.* so the
browser can show which straddle/version/flags an image was built from.

A direct `idf.py build` (not via `spangap build`) leaves the env unset; the
symbols then fall back to "(unknown)".

Usage: python3 write-build-info.py <output.c>
"""
import os
import sys


def c_string(s: str) -> str:
    """Escape an arbitrary string as a C string literal body (no quotes)."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append("\\x{:02x}".format(ord(ch) & 0xFF))
    return "".join(out)


straddle = os.environ.get("SPANGAP_BUILD_STRADDLE") or "(unknown)"
version = os.environ.get("SPANGAP_BUILD_VERSION") or "(unknown)"
args = os.environ.get("SPANGAP_BUILD_ARGS") or "(unknown)"

path = sys.argv[1]
with open(path, "w", encoding="ascii") as f:
    f.write(
        "/* Generated by spangap-core/scripts/write-build-info.py - do not edit. */\n"
        'const char app_build_straddle[] = "{}";\n'
        'const char app_build_version[]  = "{}";\n'
        'const char app_build_args[]     = "{}";\n'.format(
            c_string(straddle), c_string(version), c_string(args)
        )
    )
